version: '3.7'

services:
  server:
      build: ./Server/grpc_server
      depends_on:
        - postgres
        - client
  postgres:
    image: docker.io/bitnami/postgresql:11
    volumes:
      - .Database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=tiendita
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_PASSWORD=marihuana
  client:
    build: ./Client
    depends_on:
      - redis-server
    ports:
      - "3000:3000"
  redis-server:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - .Cache/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"